"""Embed the Google Fonts into carCrash.html as base64 @font-face rules.

Why: the game loaded Silkscreen, DotGothic16 and VT323 from fonts.googleapis.com at runtime.
That is fine for a file you open in a browser online, but a packaged offline app would fall
back to plain `monospace` everywhere and lose the whole pixel-art type treatment.

Run it again any time the fonts change:
    python tools\\embed_fonts.py

It is idempotent - the generated block sits between FONTS:BEGIN/FONTS:END markers and is
replaced wholesale on a re-run, so it never stacks up.

Two things this deliberately gets right:
  * `unicode-range` is PRESERVED on every @font-face. Without it the browser would try to use
    an embedded font for every character and draw tofu for the ones it lacks, instead of
    falling back to the next family. The game already relies on that fallback - the tutorial's
    keycap arrows (U+25B2 etc.) are outside every subset these fonts ship.
  * Only the `latin` and `latin-ext` subsets are embedded. Vietnamese/Cyrillic/Greek and
    DotGothic16's many Japanese slices are dropped: the game never renders those, and the
    Japanese ones alone would add megabytes. latin-ext is kept because it carries the Polish
    accented characters, which is a plausible future need.
"""
import base64
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GAME = ROOT / "carCrash.html"
# Batch 526 - "Jersey 10" joins for the crash text (design doc section 3A). Its tall condensed
# pixel face is the whole point of that treatment; Silkscreen cannot stand in for it.
FAMILIES = ["Silkscreen:wght@400;700", "DotGothic16", "VT323", "Jersey+10"]
KEEP_SUBSETS = {"latin", "latin-ext"}
# Google serves a different (smaller, modern) CSS to browsers that support woff2 - ask as one.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/153.0.0.0 Safari/537.36")
BEGIN = "<!-- FONTS:BEGIN (generated by tools/embed_fonts.py - do not edit by hand) -->"
END = "<!-- FONTS:END -->"


def get(url: str) -> bytes:
    return urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA}), timeout=30).read()


def font_faces() -> tuple[str, int]:
    """Fetch each family's CSS and rewrite the wanted @font-face blocks to use data: URIs."""
    out, raw_bytes = [], 0
    for family in FAMILIES:
        css = get(f"https://fonts.googleapis.com/css2?family={family}&display=swap").decode("utf-8")
        # Each block is preceded by a /* subset */ comment naming the subset it covers.
        blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css)
        if not blocks:
            sys.exit(f"No @font-face blocks parsed for {family} - has the CSS format changed?")
        kept = 0
        for subset, block in blocks:
            if subset not in KEEP_SUBSETS:
                continue
            m = re.search(r"src:\s*url\((https://[^)]+\.woff2)\)", block)
            if not m:
                continue
            data = get(m.group(1))
            raw_bytes += len(data)
            b64 = base64.b64encode(data).decode("ascii")
            uri = f"url(data:font/woff2;base64,{b64}) format('woff2')"
            out.append(re.sub(r"src:\s*url\(https://[^)]+\.woff2\)\s*format\('woff2'\)",
                              "src: " + uri, block))
            kept += 1
        if not kept:
            sys.exit(f"Kept no subsets for {family} - check KEEP_SUBSETS against the served CSS.")
        print(f"  {family}: {kept} subset(s)")
    return "\n".join(out), raw_bytes


def main() -> None:
    html = GAME.read_text(encoding="utf-8")
    print("Fetching fonts...")
    faces, raw_bytes = font_faces()
    block = f"{BEGIN}\n    <style>\n{faces}\n    </style>\n    {END}"

    if BEGIN in html:                                   # re-run: swap the generated block
        html = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block, html, flags=re.S)
    else:
        # First run. The three tags are NOT adjacent - an explanatory comment sits between the
        # preconnects and the stylesheet link - so each is handled on its own and that comment
        # is left where it is.
        html, n1 = re.subn(r'[ \t]*<link rel="preconnect" href="https://fonts\.(googleapis|gstatic)\.com"[^>]*>\n',
                           "", html)
        html, n2 = re.subn(r'[ \t]*<link href="https://fonts\.googleapis\.com/css2\?[^"]*" rel="stylesheet">',
                           lambda _: "    " + block, html)
        if (n1, n2) != (2, 1):
            sys.exit(f"Expected 2 preconnect tags and 1 stylesheet link, found {n1} and {n2}.")

    if "fonts.googleapis.com" in html or "fonts.gstatic.com" in html:
        sys.exit("A Google Fonts reference is still present - the game would still need the network.")

    GAME.write_text(html, encoding="utf-8")
    print(f"Embedded {raw_bytes / 1024:.0f} KB of woff2; carCrash.html is now "
          f"{GAME.stat().st_size / 1024:.0f} KB and needs no network for fonts.")


if __name__ == "__main__":
    main()
