"""Generate every platform's icon and launch art from the two source files in assets/.

    .venv\\Scripts\\python.exe tools\\make_app_art.py

Sources, both supplied by the user (Batch 547):
  * assets/gt-impact.ico                  the app icon, a full-bleed 256px tile with its own
                                          dark background, carrying 16/24/32/48/64/128/256 frames
  * assets/loading-impact-transparent.png the same artwork with NO background, 1920x1080

Two sources rather than one because the two jobs genuinely differ. A legacy launcher icon and the
Windows .ico are full tiles, so they want the tile art. An adaptive foreground and a launch screen
are art placed ON something else, so they want the transparent version - pasting the full tile would
put a dark square inside the adaptive icon's circular mask, which is exactly what it is not for.

This replaces make_android_icons.py, which built the same files from the traffic-cone artwork.

Everything is resized with NEAREST. The art is pixel art, and scaling pixel art by anything other
than a whole number can only blur or deform it (CHANGELOG Batches 413, 461, 498, 502). Where a
whole-number scale is available - every legacy icon below - the table picks the .ico frame that
gives one exactly.
"""
import sys
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
RES = ROOT / "mobile" / "android" / "app" / "src" / "main" / "res"

ICON = ASSETS / "gt-impact.ico"
LOGO = ASSETS / "loading-impact-transparent.png"

# The game's own --c-night. The supplied 1920x1080 splash uses exactly this.
BG_HEX = "#12161F"

# density -> (legacy px, adaptive px, .ico frame, whole-number scale to reach legacy px)
DENSITIES = [
    #  name        legacy  adaptive  frame  scale
    ("mdpi",        48,     108,      48,    1),
    ("hdpi",        72,     162,      24,    3),
    ("xhdpi",       96,     216,      48,    2),
    ("xxhdpi",     144,     324,      48,    3),
    ("xxxhdpi",    192,     432,      64,    3),
]

# An adaptive icon's outer band is masked and parallaxed however the launcher likes; only the
# inner 66/108 circle is guaranteed to survive.
SAFE_FRACTION = 66 / 108

# Android launch screen, Batch 548.
#
# It used to be eleven full-canvas splash.png files, one per orientation and density, which is what
# Capacitor ships. That is wrong for this theme: `android:background` STRETCHES a bitmap to fill the
# window, and none of those canvases match a modern phone - on a 1080x2280 screen the closest one
# (1280x1920) is squashed 29% horizontally. The artwork was being distorted, not merely drawn small.
#
# A layer-list cannot be stretched: a solid colour underneath, the logo centred on top at its own
# size. The logo then only has to exist per DENSITY, sized so it lands near 350dp wide - about 92%
# of a typical phone's ~380dp - on every one of them.
SPLASH_LOGO_DP = 350
DENSITY_SCALE = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}

# Folders whose splash.png must go, or they would override the new XML for their own configuration.
LEGACY_SPLASH_DIRS = [
    "drawable", "drawable-land-mdpi", "drawable-land-hdpi", "drawable-land-xhdpi",
    "drawable-land-xxhdpi", "drawable-land-xxxhdpi", "drawable-port-mdpi", "drawable-port-hdpi",
    "drawable-port-xhdpi", "drawable-port-xxhdpi", "drawable-port-xxxhdpi",
]

SPLASH_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/make_app_art.py. A layer-list, not a bare bitmap, because a bitmap set as
     android:background is STRETCHED to the window and would distort the artwork. -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/splash_background" />
    <item>
        <bitmap android:src="@drawable/splash_logo" android:gravity="center" />
    </item>
</layer-list>
"""

COLOUR_XML = """<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="%NAME%">%BG%</color>
</resources>
"""


def ico_frame(px):
    """One frame out of the multi-size .ico, at its native resolution."""
    im = Image.open(ICON)
    im.size = (px, px)          # Pillow selects the matching frame from this
    im.load()
    return im.convert("RGBA")


def scaled(im, factor):
    if factor == 1:
        return im
    return im.resize((im.width * factor, im.height * factor), Image.NEAREST)


def logo_cropped():
    """The transparent artwork trimmed to the pixels that are actually opaque."""
    im = Image.open(LOGO).convert("RGBA")
    box = im.getchannel("A").getbbox()
    if not box:
        sys.exit(f"{LOGO.name} is fully transparent - nothing to place")
    return im.crop(box)


def centred(canvas, art, background=None):
    w, h = canvas
    out = Image.new("RGBA", (w, h), background or (0, 0, 0, 0))
    out.alpha_composite(art, ((w - art.width) // 2, (h - art.height) // 2))
    return out


def circular(im):
    mask = Image.new("L", im.size, 0)
    ImageDraw.Draw(mask).ellipse((0, 0, im.width - 1, im.height - 1), fill=255)
    out = Image.new("RGBA", im.size, (0, 0, 0, 0))
    out.paste(im, (0, 0), mask)
    return out


def fit_within(art, max_w, max_h):
    """Largest NEAREST resize of `art` that fits the box, aspect preserved."""
    factor = min(max_w / art.width, max_h / art.height)
    w = max(1, int(art.width * factor))
    h = max(1, int(art.height * factor))
    return art.resize((w, h), Image.NEAREST)


def write_colour(path, name):
    path.write_text(COLOUR_XML.replace("%NAME%", name).replace("%BG%", BG_HEX), encoding="utf-8")


def main():
    for src in (ICON, LOGO):
        if not src.is_file():
            sys.exit(f"missing source: {src}")
    missing = [d for d, *_ in DENSITIES if not (RES / f"mipmap-{d}").is_dir()]
    if missing:
        sys.exit(f"no mipmap folder for: {', '.join(missing)} - is the android project generated?")

    logo = logo_cropped()
    written = 0

    print("launcher icons")
    for name, legacy_px, adaptive_px, frame_px, scale in DENSITIES:
        folder = RES / f"mipmap-{name}"

        tile = scaled(ico_frame(frame_px), scale)
        assert tile.width == legacy_px, f"{name}: {frame_px}x{scale} = {tile.width}, wanted {legacy_px}"
        tile.save(folder / "ic_launcher.png")
        circular(tile).save(folder / "ic_launcher_round.png")

        safe = int(adaptive_px * SAFE_FRACTION)
        fg = fit_within(logo, safe, safe)
        centred((adaptive_px, adaptive_px), fg).save(folder / "ic_launcher_foreground.png")

        written += 3
        print(f"  {name:<9} legacy {legacy_px}px (ico {frame_px}x{scale})"
              f"   adaptive {adaptive_px}px (logo {fg.width}x{fg.height} in safe {safe})")

    print("launch screen")
    for density, scale in DENSITY_SCALE.items():
        folder = RES / f"drawable-{density}"
        folder.mkdir(parents=True, exist_ok=True)
        want = int(SPLASH_LOGO_DP * scale)
        capped = want > logo.width          # never upscale; the source is all the detail there is
        art = fit_within(logo, min(want, logo.width), 10 ** 6)
        art.save(folder / "splash_logo.png")
        written += 1
        print(f"  drawable-{density:<9} logo {art.width}x{art.height}  (~{art.width / scale:.0f}dp"
              f"{', capped at source width' if capped else ''})")

    (RES / "drawable" / "splash.xml").write_text(SPLASH_XML, encoding="utf-8")
    write_colour(RES / "values" / "splash_background.xml", "splash_background")
    written += 2
    print("  drawable/splash.xml      colour + centred logo, never stretched")

    removed = 0
    for name in LEGACY_SPLASH_DIRS:
        old = RES / name / "splash.png"
        if old.is_file():
            old.unlink()
            removed += 1
    print(f"  removed {removed} stretched splash.png files")

    write_colour(RES / "values" / "ic_launcher_background.xml", "ic_launcher_background")
    written += 1
    print(f"  adaptive background -> {BG_HEX} (the game's --c-night)")
    print(f"{written} files written")


if __name__ == "__main__":
    main()
